# -*- coding: utf-8 -*-
"""Sevkiyat & Teslimat Sureleri Analiz Raporu E-posta Servisi.

Dolcezza Order Management System (Avrupa Lojistik Takip Sistemi) analiz raporunu
Dark Executive temali, Outlook & mobil uyumlu HTML e-posta olarak derler ve gonderir.
"""
from __future__ import annotations

import logging
from pathlib import Path
from jinja2 import Environment, FileSystemLoader, select_autoescape

from notify import mail

log = logging.getLogger("notify.analytics_report")

_TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "web" / "templates"
_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATE_DIR)),
    autoescape=select_autoescape(["html"]),
)


def get_default_report_payload() -> dict:
    """FA26 Europe Sevkiyat & Teslimat Sureleri Analiz Raporu verisi."""
    return {
        "subject": "FA26 Europe Sevkiyat & Teslimat Süreleri Analiz Raporu · Dolcezza Order Management System",
        "report_date": "28.08.2026",
        "source_view": "Vision_FA26_Boxed_EUROPE",
        "overall": {
            "box_count": "863",
            "item_count": "22,056",
            "country_count": 18,
            "avg_total_normal": "14.4",
            "avg_gls_normal": "3.2",
            "avg_gls_delayed": "6.1",
            "delayed_count": 87,
            "delayed_items": "2,255",
        },
        "countries": [
            {
                "name": "FR",
                "box_count": 210,
                "item_count": "6,439",
                "emc_gls": "11.8 Gün",
                "gls_normal": "2.9g",
                "gls_delayed": "7.0g",
                "gls_single": None,
                "avg_delivery": "14.6 Gün",
                "overall_delivery": "15.3g",
                "delayed_count": 37,
            },
            {
                "name": "DE",
                "box_count": 161,
                "item_count": "3,600",
                "emc_gls": "10.2 Gün",
                "gls_normal": "2.5g",
                "gls_delayed": "3.6g",
                "gls_single": None,
                "avg_delivery": "12.5 Gün",
                "overall_delivery": "12.8g",
                "delayed_count": 12,
            },
            {
                "name": "ES",
                "box_count": 108,
                "item_count": "2,990",
                "emc_gls": "12.1 Gün",
                "gls_normal": "3.8g",
                "gls_delayed": "5.0g",
                "gls_single": None,
                "avg_delivery": "15.6 Gün",
                "overall_delivery": "16.0g",
                "delayed_count": 3,
            },
            {
                "name": "AT",
                "box_count": 63,
                "item_count": "1,762",
                "emc_gls": "8.6 Gün",
                "gls_normal": "2.9g",
                "gls_delayed": "7.0g",
                "gls_single": None,
                "avg_delivery": "11.6 Gün",
                "overall_delivery": "11.6g",
                "delayed_count": 1,
            },
            {
                "name": "CZ",
                "box_count": 106,
                "item_count": "1,303",
                "emc_gls": "8.6 Gün",
                "gls_normal": "3.4g",
                "gls_delayed": "3.5g",
                "gls_single": None,
                "avg_delivery": "12.0 Gün",
                "overall_delivery": "12.0g",
                "delayed_count": 8,
            },
            {
                "name": "HU",
                "box_count": 30,
                "item_count": "1,096",
                "emc_gls": "19.3 Gün",
                "gls_normal": None,
                "gls_delayed": None,
                "gls_single": "5.6 Gün",
                "avg_delivery": "24.9 Gün",
                "overall_delivery": "24.9g",
                "delayed_count": 0,
            },
            {
                "name": "NL",
                "box_count": 38,
                "item_count": "944",
                "emc_gls": "11.6 Gün",
                "gls_normal": "1.4g",
                "gls_delayed": "4.2g",
                "gls_single": None,
                "avg_delivery": "11.1 Gün",
                "overall_delivery": "13.5g",
                "delayed_count": 5,
            },
            {
                "name": "BE",
                "box_count": 30,
                "item_count": "936",
                "emc_gls": "14.6 Gün",
                "gls_normal": "2.1g",
                "gls_delayed": "12.2g",
                "gls_single": None,
                "avg_delivery": "16.8 Gün",
                "overall_delivery": "19.1g",
                "delayed_count": 5,
            },
            {
                "name": "CI",
                "box_count": 35,
                "item_count": "695",
                "emc_gls": "2.5 Gün",
                "gls_normal": None,
                "gls_delayed": None,
                "gls_single": "3.1 Gün",
                "avg_delivery": "5.6 Gün",
                "overall_delivery": "5.6g",
                "delayed_count": 0,
            },
            {
                "name": "PL",
                "box_count": 15,
                "item_count": "505",
                "emc_gls": "10.5 Gün",
                "gls_normal": "3.9g",
                "gls_delayed": "6.0g",
                "gls_single": None,
                "avg_delivery": "13.9 Gün",
                "overall_delivery": "14.5g",
                "delayed_count": 1,
            },
            {
                "name": "SE",
                "box_count": 20,
                "item_count": "472",
                "emc_gls": "14.6 Gün",
                "gls_normal": None,
                "gls_delayed": None,
                "gls_single": "5.0 Gün",
                "avg_delivery": "19.7 Gün",
                "overall_delivery": "19.7g",
                "delayed_count": 0,
            },
            {
                "name": "IT",
                "box_count": 15,
                "item_count": "437",
                "emc_gls": "11.1 Gün",
                "gls_normal": "2.5g",
                "gls_delayed": "4.6g",
                "gls_single": None,
                "avg_delivery": "14.6 Gün",
                "overall_delivery": "14.8g",
                "delayed_count": 7,
            },
            {
                "name": "MQ",
                "box_count": 5,
                "item_count": "231",
                "emc_gls": "11.0 Gün",
                "gls_normal": None,
                "gls_delayed": None,
                "gls_single": "2.0 Gün",
                "avg_delivery": "13.0 Gün",
                "overall_delivery": "13.0g",
                "delayed_count": 0,
            },
            {
                "name": "FI",
                "box_count": 7,
                "item_count": "179",
                "emc_gls": "7.0 Gün",
                "gls_normal": "5.2g",
                "gls_delayed": "6.0g",
                "gls_single": None,
                "avg_delivery": "12.5 Gün",
                "overall_delivery": "12.4g",
                "delayed_count": 1,
            },
            {
                "name": "IL",
                "box_count": 7,
                "item_count": "135",
                "emc_gls": "2.0 Gün",
                "gls_normal": "3.0g",
                "gls_delayed": "3.0g",
                "gls_single": None,
                "avg_delivery": "5.0 Gün",
                "overall_delivery": "5.0g",
                "delayed_count": 7,
            },
            {
                "name": "EE",
                "box_count": 4,
                "item_count": "126",
                "emc_gls": "21.0 Gün",
                "gls_normal": None,
                "gls_delayed": None,
                "gls_single": "7.0 Gün",
                "avg_delivery": "28.0 Gün",
                "overall_delivery": "28.0g",
                "delayed_count": 0,
            },
            {
                "name": "GR",
                "box_count": 4,
                "item_count": "109",
                "emc_gls": "11.4 Gün",
                "gls_normal": None,
                "gls_delayed": None,
                "gls_single": "10.6 Gün",
                "avg_delivery": "21.9 Gün",
                "overall_delivery": "21.9g",
                "delayed_count": 0,
            },
            {
                "name": "PT",
                "box_count": 5,
                "item_count": "97",
                "emc_gls": "11.0 Gün",
                "gls_normal": None,
                "gls_delayed": None,
                "gls_single": "3.0 Gün",
                "avg_delivery": "14.0 Gün",
                "overall_delivery": "14.0g",
                "delayed_count": 0,
            },
        ],
        "methods": [
            {
                "name": "4th Truck Shipment",
                "box_count": 369,
                "item_count": "9,410",
                "emc_gls": "10.5 Gün",
                "gls_normal": "3.1g",
                "gls_delayed": "5.8g",
                "gls_single": None,
                "avg_delivery": "13.6 Gün",
                "overall_delivery": "14.2g",
                "delayed_count": 35,
            },
            {
                "name": "3rd Truck Shipment",
                "box_count": 231,
                "item_count": "5,880",
                "emc_gls": "11.2 Gün",
                "gls_normal": "2.8g",
                "gls_delayed": "6.2g",
                "gls_single": None,
                "avg_delivery": "14.0 Gün",
                "overall_delivery": "14.8g",
                "delayed_count": 24,
            },
            {
                "name": "7th Air Shipment",
                "box_count": 198,
                "item_count": "4,920",
                "emc_gls": "6.8 Gün",
                "gls_normal": "2.4g",
                "gls_delayed": "4.9g",
                "gls_single": None,
                "avg_delivery": "9.2 Gün",
                "overall_delivery": "9.8g",
                "delayed_count": 18,
            },
            {
                "name": "1st Truck Shipment",
                "box_count": 159,
                "item_count": "4,050",
                "emc_gls": "12.4 Gün",
                "gls_normal": "3.5g",
                "gls_delayed": "6.5g",
                "gls_single": None,
                "avg_delivery": "15.9 Gün",
                "overall_delivery": "16.5g",
                "delayed_count": 10,
            },
            {
                "name": "8th Truck Shipment",
                "box_count": 134,
                "item_count": "3,420",
                "emc_gls": "9.8 Gün",
                "gls_normal": "2.9g",
                "gls_delayed": "5.4g",
                "gls_single": None,
                "avg_delivery": "12.7 Gün",
                "overall_delivery": "13.1g",
                "delayed_count": 8,
            },
            {
                "name": "6th Air Shipment",
                "box_count": 133,
                "item_count": "3,380",
                "emc_gls": "7.2 Gün",
                "gls_normal": "2.6g",
                "gls_delayed": "4.8g",
                "gls_single": None,
                "avg_delivery": "9.8 Gün",
                "overall_delivery": "10.2g",
                "delayed_count": 6,
            },
            {
                "name": "3rd Air Shipment",
                "box_count": 109,
                "item_count": "2,780",
                "emc_gls": "8.1 Gün",
                "gls_normal": "3.0g",
                "gls_delayed": "5.2g",
                "gls_single": None,
                "avg_delivery": "11.1 Gün",
                "overall_delivery": "11.5g",
                "delayed_count": 4,
            },
        ],
        "samples": [
            {
                "customer": "BEGES1N",
                "country": "ES",
                "tracking_no": "38120177019650",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 14:10 (11g)",
                "delivered_date": "28.08.2026 17:57 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "BEGES1N",
                "country": "ES",
                "tracking_no": "38120177019667",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:28 (11g)",
                "delivered_date": "28.08.2026 17:57 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "ZVEES1N",
                "country": "ES",
                "tracking_no": "38120177020472",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 14:14 (11g)",
                "delivered_date": "28.08.2026 17:44 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "ZVEES1N",
                "country": "ES",
                "tracking_no": "38120177020489",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:06 (11g)",
                "delivered_date": "28.08.2026 17:44 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "ZVEES1N",
                "country": "ES",
                "tracking_no": "38120177020496",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:14 (11g)",
                "delivered_date": "28.08.2026 17:44 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "NAGFR1N",
                "country": "FR",
                "tracking_no": "38120177017847",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:30 (11g)",
                "delivered_date": "28.08.2026 17:31 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "NAGFR1N",
                "country": "FR",
                "tracking_no": "38120177017854",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:00 (11g)",
                "delivered_date": "28.08.2026 17:31 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "NAGFR1N",
                "country": "FR",
                "tracking_no": "38120177017861",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 14:11 (11g)",
                "delivered_date": "28.08.2026 17:31 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "NAGFR1N",
                "country": "FR",
                "tracking_no": "38120177017878",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 14:04 (11g)",
                "delivered_date": "28.08.2026 17:31 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "NAGFR1N",
                "country": "FR",
                "tracking_no": "38120177017885",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 14:16 (11g)",
                "delivered_date": "28.08.2026 17:31 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "NAGFR1N",
                "country": "FR",
                "tracking_no": "38120177017892",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 14:15 (11g)",
                "delivered_date": "28.08.2026 17:31 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "WQSCZ1N",
                "country": "CZ",
                "tracking_no": "38120177021073",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:21 (11g)",
                "delivered_date": "28.08.2026 16:18 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "WQSCZ1N",
                "country": "CZ",
                "tracking_no": "38120177021080",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:22 (11g)",
                "delivered_date": "28.08.2026 16:18 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "WQSCZ1N",
                "country": "CZ",
                "tracking_no": "38120177021097",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:15 (11g)",
                "delivered_date": "28.08.2026 16:18 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "WQSCZ1N",
                "country": "CZ",
                "tracking_no": "38120177021103",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 14:08 (11g)",
                "delivered_date": "28.08.2026 16:18 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "WQSCZ1N",
                "country": "CZ",
                "tracking_no": "38120177021110",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 14:08 (11g)",
                "delivered_date": "28.08.2026 16:18 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "WQSCZ1N",
                "country": "CZ",
                "tracking_no": "38120177021127",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:21 (11g)",
                "delivered_date": "28.08.2026 16:18 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "WQSCZ1N",
                "country": "CZ",
                "tracking_no": "38120177021134",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:21 (11g)",
                "delivered_date": "28.08.2026 16:18 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "WQSCZ1N",
                "country": "CZ",
                "tracking_no": "38120177021141",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:21 (11g)",
                "delivered_date": "28.08.2026 16:18 (3g)",
                "total_days": "14 Gün",
            },
            {
                "customer": "WQSCZ1N",
                "country": "CZ",
                "tracking_no": "38120177021158",
                "packaging_date": "14.08.2026",
                "gls_scanned": "25.08.2026 16:21 (11g)",
                "delivered_date": "28.08.2026 16:18 (3g)",
                "total_days": "14 Gün",
            },
        ],
    }


def render_html(payload: dict | None = None) -> str:
    """HTML sablonunu doldurur."""
    data = payload or get_default_report_payload()
    template = _env.get_template("mail/analytics_report.html")
    return template.render(**data)


def send_analytics_email(recipients: list[str], payload: dict | None = None) -> tuple[bool, str]:
    """Hazirlanan analiz mailini belirtilen alicilara gonderir."""
    data = payload or get_default_report_payload()
    subject = data.get("subject", "FA26 Europe Sevkiyat & Teslimat Süreleri Analiz Raporu")
    html = render_html(data)
    return mail.send(recipients, subject, html)
